language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pipenv install
  # - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report term-missing:skip-covered --cov=app --capture=sys tests